Python/django/school/apps/courses/urls.py
from django.conf.urls import url
from . import views  
urlpatterns = [
    url(r'^$', views.main, name="main"),  
    url(r'^add_course$', views.add_course, name="add_course"),
    url(r'^courses/destroy/(?P<course_id>\d+)$', views.destroy_course, name="destroy_course"),
    url(r'^delete_course/(?P<course_id>\d+)$', views.delete_course),                        
]

Python/django/school/school/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.courses.urls', namespace="course"))
]

Python/django/school/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models

class CourseManager(models.Manager):
    def basic_validator(self, postData, action): #request.post =  postData
        errors = []
        course_name = postData.get('name')
        course_description = postData.get('description')
        if action == "add_course":
            if len(course_name) < 5:
                errors.append("Course name needs to be greater than 5 letters!")
            if len(course_description) > 15:
                errors.append("Description can not be more than 15 characters!")
            if len(course_description) < 1:
                errors.append("Course description can not be blank!")
            if len(errors) == 0:
                create_course = Course.objects.create(name= course_name, description = course_description)
                return (True, create_course)
            else: 
                return (False, errors)

class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    def __repr__(self):
        return "<Course object: {} {}>".format(self.name, self.description)

    objects = CourseManager()

Python/django/school/apps/courses/views.py
from django.shortcuts import render, redirect
from .models import Course
from django.contrib import messages

def main(request):
    all_courses = Course.objects.all()
    context = {
        "all_courses": all_courses
    }
    return render(request, "courses/main.html", context)

def add_course(request):
    action = "add_course"
    valid, response = Course.objects.basic_validator(request.POST, action)
    if not valid:
        for message in response: #response has user information from database
            messages.error(request, message)
        return redirect('/')
    else:
        return redirect('/')
def destroy_course(request, course_id):
    this_course = Course.objects.filter(id = course_id)
    context  = {
        "course_info": this_course

    }
    return render(request, "courses/destroy.html", context)

def delete_course(request, course_id):
    course = Course.objects.get(id = course_id)
    course.delete()
    return redirect('/')

Python/django/school/apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete a Course</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
</head>
<body>
    <h3>Are you sure you want to delete the following course?</h3>
        {% for data in course_info %}
        <p>Name: {{data.name}}</p>
        <p>Description: {{data.description}}</p>
        <a href="/">No</a> | <a href="/delete_course/{{data.id}}">Yes</a>
        {% endfor %}
</body>
</html>

Python/django/school/apps/courses/templates/courses/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Courses</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="col">
            <h3>Add a New Course</h3>
            <form class="" action="{% url 'course:add_course' %}" method="post">
                {% csrf_token %} 
                Name: <input type="text" name="name">
                <br><br>
                Description: <input type="text" name="description">
                <br><br>
                <input type="submit">
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </ul>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Course Name</th>
                            <th>Description</th>
                            <th>Date Added</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for info in all_courses %}
                        <tr>
                            <td>{{info.name}}</td>
                            <td>{{info.description}}</td>
                            <td>{{info.created_at}}</td>
                            <td><a href="/courses/destroy/{{info.id}}">Remove</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>    
</body>
</html>